### PR TITLE
Add continuous integration using GitHub Actions

### PR DESCRIPTION
**Pull request by proski**
Run mfakto without arguments on Linux and MacOS for a quick test. Use pocl for GPU emulation.

Compile mfakto on Windows (both MSVC and MSYS2), but don't run tests due to missing pocl support.

### CODE REVIEW

**Comment by proski** [comment]
The intention of this PR is to be easy to review and to add checks that runs fast. I expect to see more checks being added in the future as we look for balance between good checks and reasonable speed.

**Comment by proski** [comment]
The CI test results can be seen at https://github.com/proski/mfakto/actions/workflows/ci.yml

**Comment by brubsby** [comment]
Looks good! Thanks for doing this. Only problem is the two Ubuntu tests seem to be failing on some branches

**Comment by proski** [comment]
> Looks good! Thanks for doing this. Only problem is the two Ubuntu tests seem to be failing on some branches

Only the master branch will have these changes. This PR should not affect other branches unless they are rebased on top of the master branch. In that case, they must be doing something wrong.

**Pull request merged**
